name: Scale Secure CI/CD

on:
  pull_request: # This makes it run every time a PR is opened

jobs:
  api-security-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Scale Secure API Tests
        uses: aniket-nikam28/scalesecure-github-action@main
        with:
          api-key: ${{ secrets.SCALESECURE_API_KEY }}
          config-file: scalesecure-tests.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
